<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PostSeeder extends Seeder
{
    public function run()
    {
        DB::table('posts')->insert([
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'The Rise of AI in Everyday Life',
                'slug' => 'rise-of-ai-everyday-life',
                'content' => 'Artificial intelligence is rapidly transforming how we interact with technology. From voice assistants to smart homes, AI is becoming an integral part of daily routines...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'AI,technology,future',
                'meta_keywords' => 'AI, automation, smart tech',
                'meta_description' => 'Exploring how AI is shaping everyday experiences.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => '10 Simple Tips for a Healthier Lifestyle',
                'slug' => '10-tips-healthier-lifestyle',
                'content' => 'Living a healthier life does not have to be complicated. Small daily habits like drinking water, exercising, and sleeping well can make a big difference...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'health,wellness,lifestyle',
                'meta_keywords' => 'healthy living, fitness, wellness',
                'meta_description' => 'Simple and effective health tips for everyday life.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'Top 5 Destinations to Visit in 2026',
                'slug' => 'top-5-destinations-2026',
                'content' => 'Travel enthusiasts are always looking for the next great destination. In 2026, several emerging locations are gaining popularity for their beauty and culture...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'travel,adventure,2026',
                'meta_keywords' => 'travel destinations, tourism',
                'meta_description' => 'Best places to travel in 2026.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'Delicious Homemade Pasta Recipe',
                'slug' => 'homemade-pasta-recipe',
                'content' => 'Making pasta at home is easier than you think. With just a few ingredients, you can create a delicious and authentic meal...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'food,recipe,pasta',
                'meta_keywords' => 'pasta recipe, homemade food',
                'meta_description' => 'Step-by-step homemade pasta recipe.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'How to Start a Small Business',
                'slug' => 'how-to-start-small-business',
                'content' => 'Starting a small business requires careful planning and execution...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'business,entrepreneurship,startup',
                'meta_keywords' => 'small business, startup tips',
                'meta_description' => 'Guide to launching your own business.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'Understanding Cloud Computing',
                'slug' => 'understanding-cloud-computing',
                'content' => 'Cloud computing has revolutionized how businesses store and access data...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'cloud,technology,data',
                'meta_keywords' => 'cloud computing, IT infrastructure',
                'meta_description' => 'Basics of cloud computing explained.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'Minimalism: Living with Less',
                'slug' => 'minimalism-living-with-less',
                'content' => 'Minimalism is about focusing on what truly matters...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'minimalism,lifestyle,simplicity',
                'meta_keywords' => 'simple living, minimalism',
                'meta_description' => 'Benefits of adopting a minimalist lifestyle.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'Saving Money in Uncertain Times',
                'slug' => 'saving-money-uncertain-times',
                'content' => 'Economic uncertainty can make saving money challenging...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'finance,saving,money',
                'meta_keywords' => 'saving tips, budgeting',
                'meta_description' => 'How to save money effectively.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'The Future of Online Learning',
                'slug' => 'future-of-online-learning',
                'content' => 'Online learning continues to grow as technology advances...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'education,online,learning',
                'meta_keywords' => 'e-learning, digital education',
                'meta_description' => 'Trends shaping online education.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'Beginner Workout Routine',
                'slug' => 'beginner-workout-routine',
                'content' => 'Starting a fitness journey can be overwhelming...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'fitness,workout,health',
                'meta_keywords' => 'exercise routine, beginner fitness',
                'meta_description' => 'Easy workout plan for beginners.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'Cybersecurity Basics Everyone Should Know',
                'slug' => 'cybersecurity-basics',
                'content' => 'Protecting your data online is more important than ever...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'cybersecurity,technology,safety',
                'meta_keywords' => 'online safety, security tips',
                'meta_description' => 'Essential cybersecurity tips.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'Budget Travel Tips for Beginners',
                'slug' => 'budget-travel-tips',
                'content' => 'Traveling on a budget does not mean sacrificing experience...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'travel,budget,tips',
                'meta_keywords' => 'cheap travel, budget trips',
                'meta_description' => 'How to travel on a budget.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'Top Street Foods Around the World',
                'slug' => 'top-street-foods-world',
                'content' => 'Street food offers a glimpse into local culture and flavors...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'food,street food,culture',
                'meta_keywords' => 'global cuisine, street eats',
                'meta_description' => 'Best street foods globally.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'Staying Motivated Every Day',
                'slug' => 'staying-motivated-daily',
                'content' => 'Motivation can fluctuate, but building habits can help...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'motivation,success,habits',
                'meta_keywords' => 'self improvement, productivity',
                'meta_description' => 'Tips to stay motivated daily.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'Why Sustainability Matters',
                'slug' => 'why-sustainability-matters',
                'content' => 'Sustainability is crucial for preserving our planet...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'environment,sustainability,green',
                'meta_keywords' => 'eco friendly, sustainability',
                'meta_description' => 'Importance of sustainable living.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'The Future of Quantum Computing',
                'slug' => 'future-of-quantum-computing',
                'content' => 'Quantum computing promises to solve complex problems far beyond the capabilities of classical computers...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'quantum,technology,future',
                'meta_keywords' => 'quantum computing, tech future',
                'meta_description' => 'An introduction to quantum computing and its potential.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'Mental Health Awareness in Modern Society',
                'slug' => 'mental-health-awareness',
                'content' => 'Mental health is just as important as physical health. Raising awareness helps reduce stigma and encourages people to seek help...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'mental health,wellness,awareness',
                'meta_keywords' => 'mental health, self care',
                'meta_description' => 'Understanding the importance of mental health.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'Exploring Hidden Gems in Africa',
                'slug' => 'hidden-gems-africa',
                'content' => 'Africa is full of breathtaking destinations that are often overlooked by tourists...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'travel,africa,adventure',
                'meta_keywords' => 'africa travel, hidden destinations',
                'meta_description' => 'Discover lesser-known travel spots in Africa.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'Healthy Smoothie Recipes',
                'slug' => 'healthy-smoothie-recipes',
                'content' => 'Smoothies are a quick and nutritious way to fuel your day...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'food,healthy,smoothie',
                'meta_keywords' => 'smoothie recipes, healthy drinks',
                'meta_description' => 'Easy and healthy smoothie recipes.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'Digital Marketing Strategies for 2026',
                'slug' => 'digital-marketing-2026',
                'content' => 'Digital marketing continues to evolve with new tools and platforms...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'marketing,digital,business',
                'meta_keywords' => 'digital marketing, SEO, social media',
                'meta_description' => 'Latest trends in digital marketing.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'Morning Routines of Successful People',
                'slug' => 'morning-routines-successful-people',
                'content' => 'How you start your morning can shape your entire day...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'lifestyle,success,habits',
                'meta_keywords' => 'morning routine, productivity',
                'meta_description' => 'Powerful morning habits for success.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'Investing for Beginners',
                'slug' => 'investing-for-beginners',
                'content' => 'Investing can seem intimidating, but with the right knowledge, anyone can start building wealth...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'finance,investing,money',
                'meta_keywords' => 'investing basics, stocks',
                'meta_description' => 'Beginner guide to investing.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'Top Skills to Learn in 2026',
                'slug' => 'top-skills-2026',
                'content' => 'The job market is evolving, and new skills are in demand...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'education,skills,career',
                'meta_keywords' => 'future skills, career growth',
                'meta_description' => 'Skills you should learn this year.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'Home Workouts Without Equipment',
                'slug' => 'home-workouts-no-equipment',
                'content' => 'You don’t need a gym to stay fit. Bodyweight exercises can be done anywhere...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'fitness,home workout,health',
                'meta_keywords' => 'bodyweight exercise, fitness at home',
                'meta_description' => 'Stay fit without gym equipment.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'The Impact of 5G Technology',
                'slug' => 'impact-of-5g-technology',
                'content' => '5G technology is set to revolutionize connectivity and communication...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => '5g,technology,network',
                'meta_keywords' => '5G network, connectivity',
                'meta_description' => 'How 5G is changing the world.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'Solo Travel: Tips and Safety Guide',
                'slug' => 'solo-travel-tips',
                'content' => 'Traveling alone can be an enriching experience...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'travel,solo,safety',
                'meta_keywords' => 'solo travel, travel safety',
                'meta_description' => 'Guide to safe solo traveling.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'Quick Dinner Ideas for Busy People',
                'slug' => 'quick-dinner-ideas',
                'content' => 'After a long day, cooking can feel like a chore...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'food,dinner,quick meals',
                'meta_keywords' => 'easy recipes, quick meals',
                'meta_description' => 'Fast and simple dinner ideas.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'Overcoming Procrastination',
                'slug' => 'overcoming-procrastination',
                'content' => 'Procrastination can hold you back from achieving your goals...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'motivation,productivity,habits',
                'meta_keywords' => 'stop procrastination, productivity tips',
                'meta_description' => 'How to beat procrastination effectively.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'Reducing Plastic Waste at Home',
                'slug' => 'reducing-plastic-waste',
                'content' => 'Reducing plastic use is one of the easiest ways to help the environment...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'environment,plastic,eco',
                'meta_keywords' => 'reduce waste, eco friendly',
                'meta_description' => 'Simple ways to reduce plastic waste.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => '1',
                'category' => '3',
                'title' => 'Remote Work: Pros and Challenges',
                'slug' => 'remote-work-pros-cons',
                'content' => 'Remote work has become more common in recent years...',
                'featured_image' => '1775564190_0.jpg',
                'tags' => 'remote work,business,career',
                'meta_keywords' => 'work from home, productivity',
                'meta_description' => 'Advantages and drawbacks of remote work.',
                'visibility' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
